package net.andreynikolaev.anweb.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import net.andreynikolaev.anweb.db.ProfileDetails;
import net.andreynikolaev.anweb.db.Profiles;

/**
 * Class _LangList was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LangList extends CayenneDataObject {

    @Deprecated
    public static final String ID_PROPERTY = "ID";
    @Deprecated
    public static final String LANG_NATIVE_NAME_PROPERTY = "langNativeName";
    @Deprecated
    public static final String LOCALE_NAME_PROPERTY = "localeName";
    @Deprecated
    public static final String PROFILE_PROPERTY = "profile";
    @Deprecated
    public static final String TO_LANG_PROPERTY = "toLang";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Integer> ID = new Property<Integer>("ID");
    public static final Property<String> LANG_NATIVE_NAME = new Property<String>("langNativeName");
    public static final Property<String> LOCALE_NAME = new Property<String>("localeName");
    public static final Property<List<Profiles>> PROFILE = new Property<List<Profiles>>("profile");
    public static final Property<List<ProfileDetails>> TO_LANG = new Property<List<ProfileDetails>>("toLang");

    public void setID(Integer ID) {
        writeProperty("ID", ID);
    }
    public Integer getID() {
        return (Integer)readProperty("ID");
    }

    public void setLangNativeName(String langNativeName) {
        writeProperty("langNativeName", langNativeName);
    }
    public String getLangNativeName() {
        return (String)readProperty("langNativeName");
    }

    public void setLocaleName(String localeName) {
        writeProperty("localeName", localeName);
    }
    public String getLocaleName() {
        return (String)readProperty("localeName");
    }

    public void addToProfile(Profiles obj) {
        addToManyTarget("profile", obj, true);
    }
    public void removeFromProfile(Profiles obj) {
        removeToManyTarget("profile", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profiles> getProfile() {
        return (List<Profiles>)readProperty("profile");
    }


    public void addToToLang(ProfileDetails obj) {
        addToManyTarget("toLang", obj, true);
    }
    public void removeFromToLang(ProfileDetails obj) {
        removeToManyTarget("toLang", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ProfileDetails> getToLang() {
        return (List<ProfileDetails>)readProperty("toLang");
    }


}
