package net.andreynikolaev.anweb.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import net.andreynikolaev.anweb.db.Experience;
import net.andreynikolaev.anweb.db.LangList;
import net.andreynikolaev.anweb.db.Profiles;
import net.andreynikolaev.anweb.db.SkillsGroup;

/**
 * Class _ProfileDetails was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ProfileDetails extends CayenneDataObject {

    @Deprecated
    public static final String FIRST_NAME_PROPERTY = "firstName";
    @Deprecated
    public static final String INFO_PROPERTY = "info";
    @Deprecated
    public static final String LAST_NAME_PROPERTY = "lastName";
    @Deprecated
    public static final String SHOW_PROPERTY = "show";
    @Deprecated
    public static final String TITLE1_PROPERTY = "title1";
    @Deprecated
    public static final String TITLE2_PROPERTY = "title2";
    @Deprecated
    public static final String EXPERIENCES_PROPERTY = "experiences";
    @Deprecated
    public static final String LANG_PROPERTY = "lang";
    @Deprecated
    public static final String PROFILE_PROPERTY = "profile";
    @Deprecated
    public static final String SKILLS_GROUPS_PROPERTY = "skillsGroups";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> FIRST_NAME = new Property<String>("firstName");
    public static final Property<String> INFO = new Property<String>("info");
    public static final Property<String> LAST_NAME = new Property<String>("lastName");
    public static final Property<Boolean> SHOW = new Property<Boolean>("show");
    public static final Property<String> TITLE1 = new Property<String>("title1");
    public static final Property<String> TITLE2 = new Property<String>("title2");
    public static final Property<List<Experience>> EXPERIENCES = new Property<List<Experience>>("experiences");
    public static final Property<LangList> LANG = new Property<LangList>("lang");
    public static final Property<Profiles> PROFILE = new Property<Profiles>("profile");
    public static final Property<List<SkillsGroup>> SKILLS_GROUPS = new Property<List<SkillsGroup>>("skillsGroups");

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setInfo(String info) {
        writeProperty("info", info);
    }
    public String getInfo() {
        return (String)readProperty("info");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setShow(Boolean show) {
        writeProperty("show", show);
    }
    public Boolean getShow() {
        return (Boolean)readProperty("show");
    }

    public void setTitle1(String title1) {
        writeProperty("title1", title1);
    }
    public String getTitle1() {
        return (String)readProperty("title1");
    }

    public void setTitle2(String title2) {
        writeProperty("title2", title2);
    }
    public String getTitle2() {
        return (String)readProperty("title2");
    }

    public void addToExperiences(Experience obj) {
        addToManyTarget("experiences", obj, true);
    }
    public void removeFromExperiences(Experience obj) {
        removeToManyTarget("experiences", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Experience> getExperiences() {
        return (List<Experience>)readProperty("experiences");
    }


    public void setLang(LangList lang) {
        setToOneTarget("lang", lang, true);
    }

    public LangList getLang() {
        return (LangList)readProperty("lang");
    }


    public void setProfile(Profiles profile) {
        setToOneTarget("profile", profile, true);
    }

    public Profiles getProfile() {
        return (Profiles)readProperty("profile");
    }


    public void addToSkillsGroups(SkillsGroup obj) {
        addToManyTarget("skillsGroups", obj, true);
    }
    public void removeFromSkillsGroups(SkillsGroup obj) {
        removeToManyTarget("skillsGroups", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SkillsGroup> getSkillsGroups() {
        return (List<SkillsGroup>)readProperty("skillsGroups");
    }


}
