package net.andreynikolaev.anweb.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import net.andreynikolaev.anweb.db.ProfileDetails;
import net.andreynikolaev.anweb.db.Skills;

/**
 * Class _SkillsGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SkillsGroup extends CayenneDataObject {

    @Deprecated
    public static final String GROUP_NAME_PROPERTY = "groupName";
    @Deprecated
    public static final String SHOW_PROPERTY = "show";
    @Deprecated
    public static final String SHOW_POSITION_PROPERTY = "showPosition";
    @Deprecated
    public static final String PROFILE_DETAIL_PROPERTY = "profileDetail";
    @Deprecated
    public static final String SKILLS_PROPERTY = "skills";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> GROUP_NAME = new Property<String>("groupName");
    public static final Property<Boolean> SHOW = new Property<Boolean>("show");
    public static final Property<Integer> SHOW_POSITION = new Property<Integer>("showPosition");
    public static final Property<ProfileDetails> PROFILE_DETAIL = new Property<ProfileDetails>("profileDetail");
    public static final Property<List<Skills>> SKILLS = new Property<List<Skills>>("skills");

    public void setGroupName(String groupName) {
        writeProperty("groupName", groupName);
    }
    public String getGroupName() {
        return (String)readProperty("groupName");
    }

    public void setShow(Boolean show) {
        writeProperty("show", show);
    }
    public Boolean getShow() {
        return (Boolean)readProperty("show");
    }

    public void setShowPosition(Integer showPosition) {
        writeProperty("showPosition", showPosition);
    }
    public Integer getShowPosition() {
        return (Integer)readProperty("showPosition");
    }

    public void setProfileDetail(ProfileDetails profileDetail) {
        setToOneTarget("profileDetail", profileDetail, true);
    }

    public ProfileDetails getProfileDetail() {
        return (ProfileDetails)readProperty("profileDetail");
    }


    public void addToSkills(Skills obj) {
        addToManyTarget("skills", obj, true);
    }
    public void removeFromSkills(Skills obj) {
        removeToManyTarget("skills", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Skills> getSkills() {
        return (List<Skills>)readProperty("skills");
    }


}
