package net.andreynikolaev.anweb.db.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import net.andreynikolaev.anweb.db.SkillsGroup;

/**
 * Class _Skills was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Skills extends CayenneDataObject {

    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String RATING_PROPERTY = "rating";
    @Deprecated
    public static final String SHOW_PROPERTY = "show";
    @Deprecated
    public static final String SHOW_POSITION_PROPERTY = "showPosition";
    @Deprecated
    public static final String SKILLS_GROUP_PROPERTY = "skillsGroup";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<Integer> RATING = new Property<Integer>("rating");
    public static final Property<Boolean> SHOW = new Property<Boolean>("show");
    public static final Property<Integer> SHOW_POSITION = new Property<Integer>("showPosition");
    public static final Property<SkillsGroup> SKILLS_GROUP = new Property<SkillsGroup>("skillsGroup");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setRating(Integer rating) {
        writeProperty("rating", rating);
    }
    public Integer getRating() {
        return (Integer)readProperty("rating");
    }

    public void setShow(Boolean show) {
        writeProperty("show", show);
    }
    public Boolean getShow() {
        return (Boolean)readProperty("show");
    }

    public void setShowPosition(Integer showPosition) {
        writeProperty("showPosition", showPosition);
    }
    public Integer getShowPosition() {
        return (Integer)readProperty("showPosition");
    }

    public void setSkillsGroup(SkillsGroup skillsGroup) {
        setToOneTarget("skillsGroup", skillsGroup, true);
    }

    public SkillsGroup getSkillsGroup() {
        return (SkillsGroup)readProperty("skillsGroup");
    }


}
