package net.andreynikolaev.anweb.db.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Statistik was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Statistik extends CayenneDataObject {

    @Deprecated
    public static final String AGENT_PROPERTY = "agent";
    @Deprecated
    public static final String AGENT_LANG_PROPERTY = "agentLang";
    @Deprecated
    public static final String IPADDR_PROPERTY = "ipaddr";
    @Deprecated
    public static final String LAST_ACCESS_PROPERTY = "lastAccess";
    @Deprecated
    public static final String LOGIN_NAME_PROPERTY = "loginName";
    @Deprecated
    public static final String NAV_HISTORY_PROPERTY = "navHistory";
    @Deprecated
    public static final String SESSIONID_PROPERTY = "sessionid";
    @Deprecated
    public static final String TIMEACCESS_PROPERTY = "timeaccess";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> AGENT = new Property<String>("agent");
    public static final Property<String> AGENT_LANG = new Property<String>("agentLang");
    public static final Property<String> IPADDR = new Property<String>("ipaddr");
    public static final Property<Date> LAST_ACCESS = new Property<Date>("lastAccess");
    public static final Property<String> LOGIN_NAME = new Property<String>("loginName");
    public static final Property<String> NAV_HISTORY = new Property<String>("navHistory");
    public static final Property<String> SESSIONID = new Property<String>("sessionid");
    public static final Property<Date> TIMEACCESS = new Property<Date>("timeaccess");

    public void setAgent(String agent) {
        writeProperty("agent", agent);
    }
    public String getAgent() {
        return (String)readProperty("agent");
    }

    public void setAgentLang(String agentLang) {
        writeProperty("agentLang", agentLang);
    }
    public String getAgentLang() {
        return (String)readProperty("agentLang");
    }

    public void setIpaddr(String ipaddr) {
        writeProperty("ipaddr", ipaddr);
    }
    public String getIpaddr() {
        return (String)readProperty("ipaddr");
    }

    public void setLastAccess(Date lastAccess) {
        writeProperty("lastAccess", lastAccess);
    }
    public Date getLastAccess() {
        return (Date)readProperty("lastAccess");
    }

    public void setLoginName(String loginName) {
        writeProperty("loginName", loginName);
    }
    public String getLoginName() {
        return (String)readProperty("loginName");
    }

    public void setNavHistory(String navHistory) {
        writeProperty("navHistory", navHistory);
    }
    public String getNavHistory() {
        return (String)readProperty("navHistory");
    }

    public void setSessionid(String sessionid) {
        writeProperty("sessionid", sessionid);
    }
    public String getSessionid() {
        return (String)readProperty("sessionid");
    }

    public void setTimeaccess(Date timeaccess) {
        writeProperty("timeaccess", timeaccess);
    }
    public Date getTimeaccess() {
        return (Date)readProperty("timeaccess");
    }

}
